### ISSUE TITLE
Compatibility with RC2014 mini?

### ISSUE THREAD

**Issue by andreacampanella** [robdobsn/PiBusRaider#1]
I was wondering how much work would it be to make it work with the RC2014 mini , I would love to have a compact 2-boards layout :)

**Comment by robdobsn** [comment]
It doesn't look as though BUSRQ and BUSACK are brought out anywhere on the mini. I guess they could be soldered directly to the Z80 processor pins but it would be a bit of a hack. However it isn't clear to me what the 40 pin connector is doing on the mini. It looks like a Pi connector but I assume in that case only for the serial IO functionality?

**Comment by andreacampanella** [comment]
I don't think anyone would be scared about 2 flying leads if they soldered the entire board themselves. 

Yes, the 40 pin connector is only for serial port functionality ( http://rc2014.co.uk/wp-content/uploads/2016/10/RC2014-Mini.pdf )

**Comment by robdobsn** [comment]
Ok, well in that case I think it is viable. I'm considering trying to put a kit together for the BusRaider. Is that something you would be interested in? It's quite a bit of work to gather together all the components but I'd be happy to do it if a few people might be interested.

**Comment by andreacampanella** [comment]
I would interested into buy one, I would love to have a zx spectrum clone, which bring me to the next problem, ram, but according to Spencer I can just remove the bank and use a normal ram expansion.

Perhaps wold be better to have an adaptor board ?

**Comment by andreacampanella** [comment]
I think this could be extended to the new rc2014 micro too.

**Comment by robdobsn** [comment]
Hi Andrea
It is a little frustrating that the RC2014 Micro has been designed with only the single-row bus and none of the other signals are easy to get to. I don't think the cost would have been increased significantly by having the full bus available and that would have allowed cards like the BusRaider (which uses BUSRQ and BUSACK to gain access to the bus) to operate. Without quite a bit of hacking I can't really see a way to use the RC2014 Micro with BusRaider.
Let me know if you have any thoughts on this.
Best wishes
Rob

**Comment by andreacampanella** [comment]
How much hacking are we talking about?

**Comment by robdobsn** [comment]
This thread is very old but I have just been working on getting BusRaider working on some other systems. It seems that it is possible in some cases - where BUSRQ and BUSACK are available and open-drain, WAIT is open-drain and there is some way to disable memory forcing data onto the bus. I have also created a new processor motherboard using Z180 as I wanted to have a way to use BusRaider plug-and-play and everything so far has required a little hacking to enable the full functionality. I'll let you know when the PCB is done for the Z180 motherboard if you are interested.
