### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by EtchedPixels** [robdobsn/PiBusRaider#2]
The documentation PDF link on the readme.md doesn't work.

**Comment by robdobsn** [comment]
Hi Alan

I’ve fixed that now, let me know if you find anything else broken or need any help.

I think the easiest way to get started is to plug an HDMI cable and USB keyboard into the Pi (requires a couple of adapters unfortunately – a USB OTG one for a full sized USB A connector and an HDMI converter for the smaller HDMI connector on a Pi Zero). Hopefully you will have these if you have used an RC2014 PiGFX board. Also, the USB support is sketchy – some keyboards work and some don’t. Then plug into a PRO bus and power up.

You should see confirmation of keyboard OK and ESP32 Version showing on the HDMI display.

Once you have HDMI and keyboard working you can press F2 and get “immediate mode” on the Pi software. Then type:

w/yourssid/yourwifipw/ahostname

and enter.

The ESP32 should then go away and connect to your WiFi and the IP address should appear on the HDMI display.

Then you can open a browser and navigate to:

http://thebusraiderip

This should open the BusRaider Web UI.

Then you can select a machine – the serial terminal ones work ok with RomWBW on the 512K RAM/ROM and the TRS80 / ZX Spectrum should be ok with any linear 64K RAM board.

Then drag and drop programs (such as level1.rom for TRS80 or 48k.rom for ZX Spectrum) to run immediately or store on the SPIFFS file system and run from there.

There’s more info in the manual about configuring other features – such as UART emulation for 6850 and creating a demo.json file so you can use the demo button (below the ESP RESET button) to cycle through demo setups.

Let me know how you get on.

Best

Rob

Rob Dobson FIET
rob@dobson.com
+44 7770 866452
http://LinkedIn.com/in/robdobsn
@robdobsn www.robdobson.com

________________________________

**Comment by EtchedPixels** [comment]
Thanks

www.robdobson.com is also broken btw 8) - without the www works, with the www fails the SSL cert check 8)

**Comment by robdobsn** [comment]
Hi Alan, this is fixed now, thanks Rob
