### ISSUE TITLE
Cannot compile McZXSpectrum.cpp

### ISSUE THREAD

**Issue by Grumpy666** [robdobsn/PiBusRaider#5]
When trying to compile the PiSw I get a compilation error:

PiSw/src/Machines/McZXSpectrum.cpp:230:22: error: 'pixDisp' was not declared in this scope
  230 |                 if (!pixDisp)
      |                      ^~~~~~~

Where should that variable be declared?

**Comment by robdobsn** [comment]
This code was a hang-over from previous work and isn't needed any more. The modified file should have been checked in but unfortunately it wasn't. The code is now commented out and the build now succeeds again.
